import Mathlib

/-!
# Discussion: §2.2 Ideals in Localizations of Rings

The book introduces contraction and extension of ideals through ring
homomorphisms, then specializes to the localization setting B = S⁻¹A.

1. **Contraction**: φ⁻¹(𝔟) is an A-ideal (`Ideal.comap`).
2. **Extension**: 𝔞B = ideal generated by φ(𝔞) (`Ideal.map`).
3. **𝔞 ⊆ 𝔞ᵉᶜ**: Contraction of the extension contains the original.
4. **𝔟ᶜᵉ ⊆ 𝔟**: Extension of the contraction is contained in the original.
5. **𝔞ᵉ = B when 𝔞 ∩ S ≠ ∅**: If an ideal meets S, its extension is the whole ring.
6. **𝔟ᶜᵉ = 𝔟 when B = S⁻¹A**: For localizations, extension-contraction recovers 𝔟.

See `blobs/Lecture2/02_00b_Discussion.md` for the source text.
-/

section Ideals_in_Localizations_2_2

/-! ## Claim 1: Contraction φ⁻¹(𝔟) is an A-ideal

For any ring homomorphism φ : R → S and ideal 𝔟 of S, the preimage
φ⁻¹(𝔟) is an ideal of R. Mathlib calls this `Ideal.comap`. -/

recall Ideal.comap

/-! ## Claim 2: Extension 𝔞B = ideal generated by φ(𝔞)

For a ring homomorphism φ : R → S and ideal 𝔞 of R, the extension
𝔞ᵉ is the ideal of S generated by φ(𝔞). Mathlib calls this `Ideal.map`. -/

recall Ideal.map

/-! ## Claim 3: 𝔞 ⊆ 𝔞ᵉᶜ

Every element of 𝔞 is in the contraction of its extension. This holds
for arbitrary ring homomorphisms, not just localizations. -/

recall Ideal.le_comap_map

/-! ## Claim 4: 𝔟ᶜᵉ ⊆ 𝔟

The extension of the contraction is contained in the original. This also
holds for arbitrary ring homomorphisms. -/

recall Ideal.map_comap_le

/-! ## Claim 5: 𝔞ᵉ = S when 𝔞 ∩ S ≠ ∅

If an ideal 𝔞 of R contains an element of the multiplicative set M
(i.e., 𝔞 ∩ M ≠ ∅), then its extension to the localization is the
entire ring. Equivalently, 𝔞ᵉ ≠ ⊤ iff 𝔞 and M are disjoint. -/

recall IsLocalization.map_algebraMap_ne_top_iff_disjoint

-- Contrapositive: if 𝔞 meets M, then 𝔞ᵉ = ⊤
variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
variable {M : Submonoid R} [IsLocalization M S]

theorem ideal_ext_eq_top_of_meets_submonoid
    (I : Ideal R) (h : ¬Disjoint (M : Set R) (I : Set R)) :
    Ideal.map (algebraMap R S) I = ⊤ := by
  by_contra h_ne
  exact h ((IsLocalization.map_algebraMap_ne_top_iff_disjoint M S I).mp h_ne)

/-! ## Claim 6: 𝔟ᶜᵉ = 𝔟 when B = S⁻¹A

For localizations (unlike general ring homomorphisms), extending the
contraction always recovers the original ideal. This is the key property
that makes contraction/extension a well-behaved correspondence for
localizations. -/

recall IsLocalization.map_comap

end Ideals_in_Localizations_2_2
