import Mathlib
import SutherlandNumberTheoryLecture1

/-!
# Example 2.5: ℤ_(p) is a DVR

Let p ∈ ℤ be a prime. Then ℤ_(p) = {a/b : a, b ∈ ℤ, p ∤ b}. As in the previous
example, ℤ is a PID and ℤ_(p) is a DVR; the valuation on ℚ is the p-adic valuation.
The residue field is ℤ_(p)/pℤ_(p) ≃ 𝔽_p and the quotient map is reduction mod p.

## Proof strategy (from the book)

ℤ is a PID → ℤ is a Dedekind domain → ��_(p) is a DVR.
In Mathlib: `Int.instIsPrincipalIdealRing` + `IsPrincipalIdealRing.isDedekindDomain`
+ `IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain`.

## Lecture 1 references

- `IsDVR` (01_10): wraps `IsDiscreteValuationRing`
- `sutherland_theorem1_16_localPID_isDVR` (01_16): local PID (not a field) ⟹ DVR
- `zLocAtP_isLocalRing` (01_14): ℤ_(p) is a local ring
- `primeIdealZ_isPrime` (01_14): (p) is prime in ℤ
- `padicValuation` (01_07): p-adic valuation on ℚ

See `blobs/Lecture2/02_05_Example.md` for the source text.
-/

section Example_2_5

/-! ### The prime ideal (p) in ��

The ideal generated by a prime p in ℤ is a prime ideal.
This is established in Lecture 1 (Example 1.14) as `primeIdealZ_isPrime`. -/

-- Recall from Lecture 1: (p) is prime in ℤ
#check @primeIdealZ_isPrime

/-! ### The localization ℤ_(p)

ℤ_(p) = {a/b : a, b ∈ ℤ, p ∤ b} is the localization of ℤ at the prime ideal (p).
Lecture 1 (Example 1.14) shows this is a local ring. -/

variable (p : ℕ) [hp : Fact p.Prime]

/-- The prime ideal (p) in ℤ. -/
noncomputable def intPrimeIdeal_p : Ideal ℤ :=
  Ideal.span {(p : ℤ)}

/-- (p) is a prime ideal in ℤ. -/
instance intPrimeIdeal_p_isPrime : (intPrimeIdeal_p p).IsPrime := by
  rw [intPrimeIdeal_p, Ideal.span_singleton_prime (by exact_mod_cast hp.out.ne_zero)]
  exact Nat.prime_iff_prime_int.mp hp.out

/-- ℤ_(p): the localization of ℤ at the prime ideal (p). -/
noncomputable abbrev Z_loc_p : Type :=
  Localization.AtPrime (intPrimeIdeal_p p)

-- Recall from Lecture 1: ℤ_(p) is a local ring
#check @zLocAtP_isLocalRing

/-! ### ℤ is a PID

This is a standard Mathlib fact. Since PIDs are Dedekind domains, we get the
DVR result. -/

-- ℤ is a PID
#check (inferInstance : IsPrincipalIdealRing ℤ)

/-! ### ℤ_(p) is a DVR

The key result: since ��� is a PID (hence Dedekind domain), and (p) is a nonzero
prime ideal, the localization ℤ_(p) is a DVR. -/

/-- (p) ≠ 0 in ℤ, so the ideal (p) is nonzero. -/
theorem intPrimeIdeal_p_ne_bot : intPrimeIdeal_p p ≠ ⊥ := by
  rw [intPrimeIdeal_p, Ne, Ideal.span_singleton_eq_bot]
  exact_mod_cast hp.out.ne_zero

/-- ℤ_(p) is a DVR (Example 2.5).
Proof: ℤ is a PID → Dedekind domain. Localization of a Dedekind domain
at a nonzero prime ideal is a DVR. -/
instance Z_loc_p_isDVR : IsDiscreteValuationRing (Z_loc_p p) :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
    ℤ (intPrimeIdeal_p_ne_bot p) (Z_loc_p p)

/-- ℤ_(p) is a DVR in the sense of Sutherland Def 1.10 (Lecture 1). -/
theorem Z_loc_p_isDVR' : IsDVR (Z_loc_p p) :=
  Z_loc_p_isDVR p

/-! ### The p-adic valuation

The valuation on ℚ = Frac(ℤ) corresponding to the valuation ring ℤ_(p) is the
p-adic valuation. Recall from Lecture 1 (Definition 1.7): -/

-- Recall: p-adic valuation on ℚ
#check @padicValuation

/-! ### Residue field

The residue field is ℤ_(p)/pℤ_(p) ≃ ���_p = ℤ/pℤ, and the quotient map is
reduction modulo p. -/

/-- The residue field of ℤ_(p) is isomorphic to 𝔽_p = ℤ/pℤ. -/
theorem Z_loc_p_residueField :
    Nonempty (IsLocalRing.ResidueField (Z_loc_p p) ≃+* ZMod p) := by
  sorry

end Example_2_5
