import Mathlib
import SutherlandNumberTheoryLecture1

/-!
# Example 2.4: k[x]_(x-2) is a DVR

For a field k, let A = k[x] and 𝔭 = (x - 2). Then A_𝔭 = {f ∈ k(x) : f is defined at 2}
is a DVR. The ring k[x] is a PID, so A_𝔭 is a PID with a unique nonzero maximal ideal,
hence a DVR (by Theorem 1.16). Its maximal ideal is 𝔭A_𝔭 = {f ∈ k(x) : f(2) = 0}.
The residue field is A_𝔭/𝔭A_𝔭 ≃ k, and the quotient map sends f to f(2).

## Proof strategy (from the book)

k[x] is a PID → k[x] is a Dedekind domain → k[x]_(x-2) is a DVR.
In Mathlib: `Polynomial.instIsPrincipalIdealRing` + `IsPrincipalIdealRing.isDedekindDomain`
+ `IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain`.

## Lecture 1 references

- `IsDVR` (01_10): wraps `IsDiscreteValuationRing`
- `sutherland_theorem1_16_localPID_isDVR` (01_16): local PID (not a field) ⟹ DVR

See `blobs/Lecture2/02_04_Example.md` for the source text.
-/

open Polynomial

section Example_2_4

variable (k : Type*) [Field k]

/-! ### The prime ideal (x - 2) in k[x]

The ideal generated by (X - C 2) in k[x] is prime because X - C 2 is irreducible
(it has degree 1). -/

/-- The prime ideal 𝔭 = (x - 2) in k[x]. -/
noncomputable def polyPrimeIdeal_x_sub_2 : Ideal k[X] :=
  Ideal.span {X - C 2}

/-- (x - 2) is a prime element in k[x]. -/
theorem x_sub_2_prime : Prime (X - C 2 : k[X]) :=
  Polynomial.prime_of_degree_eq_one (by simp [Polynomial.degree_X_sub_C])

/-- The ideal (x - 2) is a prime ideal in k[x]. -/
instance polyPrimeIdeal_x_sub_2_isPrime :
    (polyPrimeIdeal_x_sub_2 k).IsPrime := by
  rw [polyPrimeIdeal_x_sub_2, Ideal.span_singleton_prime (X_sub_C_ne_zero 2)]
  exact x_sub_2_prime k

/-! ### The localization k[x]_(x-2)

The localization of k[x] at the prime ideal (x - 2). -/

/-- k[x]_(x-2): the localization of k[x] at the prime ideal (x - 2). -/
noncomputable abbrev kx_loc_x_sub_2 : Type _ :=
  Localization.AtPrime (polyPrimeIdeal_x_sub_2 k)

/-! ### k[x] is a PID

This is a standard Mathlib fact: polynomial rings over fields are PIDs.
Since PIDs are Dedekind domains, we get the DVR result from Mathlib's
`IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain`. -/

-- k[x] is a PID
#check (inferInstance : IsPrincipalIdealRing k[X])

-- PID → Dedekind domain (Mathlib instance)
#check @IsPrincipalIdealRing.isDedekindDomain

-- Localization of Dedekind domain at nonzero prime → DVR
#check @IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain

/-! ### k[x]_(x-2) is a DVR

The key result: since k[x] is a PID (hence Dedekind domain), and (x-2) is a
nonzero prime ideal, the localization k[x]_(x-2) is a DVR. -/

/-- (x - 2) ≠ 0 in k[x], so the ideal (x-2) is nonzero (i.e., ⊥ < 𝔭). -/
theorem polyPrimeIdeal_x_sub_2_ne_bot :
    polyPrimeIdeal_x_sub_2 k ≠ ⊥ := by
  rw [polyPrimeIdeal_x_sub_2, Ne, Ideal.span_singleton_eq_bot]
  exact X_sub_C_ne_zero 2

/-- k[x]_(x-2) is a DVR (Example 2.4).
Proof: k[x] is a PID → Dedekind domain. Localization of a Dedekind domain
at a nonzero prime ideal is a DVR. -/
instance kx_loc_x_sub_2_isDVR :
    IsDiscreteValuationRing (kx_loc_x_sub_2 k) :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain
    k[X] (polyPrimeIdeal_x_sub_2_ne_bot k) (kx_loc_x_sub_2 k)

/-! ### Maximal ideal characterization

The maximal ideal of k[x]_(x-2) is the extension of (x-2) to the localization.
It consists of rational functions that vanish at 2. -/

/-- The maximal ideal of k[x]_(x-2) is the extension of (x-2) to the localization.
This is the unique nonzero maximal ideal of the DVR. -/
theorem kx_loc_x_sub_2_maximalIdeal :
    IsLocalRing.maximalIdeal (kx_loc_x_sub_2 k) =
      (polyPrimeIdeal_x_sub_2 k).map (algebraMap k[X] (kx_loc_x_sub_2 k)) := by
  exact Localization.AtPrime.map_eq_maximalIdeal.symm

/-! ### Residue field

The residue field of k[x]_(x-2) is isomorphic to k. The quotient map sends f to f(2).
This follows because the residue field of a localization at a prime 𝔭 generated by
a degree-1 polynomial over a field k is k itself. -/

/-- (x - 2) is a maximal ideal in k[x] (since k[x] is a PID and x-2 is irreducible). -/
instance polyPrimeIdeal_x_sub_2_isMaximal :
    (polyPrimeIdeal_x_sub_2 k).IsMaximal :=
  Ideal.IsPrime.isMaximal inferInstance (polyPrimeIdeal_x_sub_2_ne_bot k)

/-- The residue field of k[x]_(x-2) is isomorphic to k. -/
theorem kx_loc_x_sub_2_residueField :
    Nonempty (IsLocalRing.ResidueField (kx_loc_x_sub_2 k) ≃+* k) := by
  -- ResidueField(k[x]_(x-2)) ≃ k[X]/(X-2) ≃ k
  have e1 : k[X] ⧸ polyPrimeIdeal_x_sub_2 k ≃+* IsLocalRing.ResidueField (kx_loc_x_sub_2 k) :=
    IsLocalization.AtPrime.equivQuotMaximalIdeal (polyPrimeIdeal_x_sub_2 k) (kx_loc_x_sub_2 k)
  have e2 : (k[X] ⧸ Ideal.span ({X - C 2} : Set k[X])) ≃+* k :=
    (Polynomial.quotientSpanXSubCAlgEquiv (R := k) 2).toRingEquiv
  exact ⟨e1.symm.trans e2⟩

/-- The quotient map k[x]_(x-2) → k sends f to its evaluation at 2.
More precisely, the composition k[x] → k[x]_(x-2) → residue field ≃ k
agrees with evaluation at 2. -/
theorem kx_loc_x_sub_2_quotientMap_eq_eval :
    ∀ f : k[X],
      IsLocalRing.residue (kx_loc_x_sub_2 k)
        (algebraMap k[X] (kx_loc_x_sub_2 k) f) =
      algebraMap k (IsLocalRing.ResidueField (kx_loc_x_sub_2 k)) (Polynomial.eval 2 f) := by
  intro f
  -- f - C(eval 2 f) is divisible by (X - C 2), hence in 𝔭
  have hmem : f - C (Polynomial.eval 2 f) ∈ polyPrimeIdeal_x_sub_2 k := by
    rw [polyPrimeIdeal_x_sub_2, Ideal.mem_span_singleton]
    exact dvd_iff_isRoot.mpr (by simp [IsRoot])
  -- So its image under algebraMap is in the maximal ideal, killed by residue
  have hzero : IsLocalRing.residue (kx_loc_x_sub_2 k)
      (algebraMap k[X] (kx_loc_x_sub_2 k) (f - C (Polynomial.eval 2 f))) = 0 := by
    rw [IsLocalRing.residue_eq_zero_iff, kx_loc_x_sub_2_maximalIdeal]
    exact Ideal.mem_map_of_mem _ hmem
  -- Expand and rearrange to get residue(algebraMap f) = residue(algebraMap(C(eval 2 f)))
  rw [map_sub] at hzero
  rw [map_sub] at hzero
  have hzero' := sub_eq_zero.mp hzero
  rw [hzero']
  -- Goal: residue(algebraMap(C(eval 2 f))) = algebraMap k ResidueField (eval 2 f)
  -- This follows from the scalar tower k → k[X] → loc → ResidueField
  -- Goal: residue(algebraMap_{k[X]}(C(eval 2 f))) = residue(algebraMap_{k}(eval 2 f))
  -- C a = algebraMap k k[X] a, and scalar tower gives the rest
  rw [Polynomial.C_eq_algebraMap,
      ← IsScalarTower.algebraMap_apply k k[X] (kx_loc_x_sub_2 k),
      IsScalarTower.algebraMap_apply k (kx_loc_x_sub_2 k)
        (IsLocalRing.ResidueField (kx_loc_x_sub_2 k)),
      IsLocalRing.ResidueField.algebraMap_eq]

end Example_2_4
