import Mathlib

/-!
# Discussion: ideal localization equals ideal extension

When K = Frac A and M is an A-submodule of K (in particular, an ideal I of A),
the localization of I as an A-module at a prime 𝔭 equals the extension of I
to A_𝔭:

  I_𝔭 = {i/s : i ∈ I, s ∈ A \ 𝔭} = IA_𝔭

## Claims formalized

1. I_𝔭 = IA_𝔭 — the localization of an ideal as a module equals its extension
   as an ideal → `Algebra.idealMap_isLocalizedModule` (recall)

See `blobs/Lecture2/02_06a_Discussion.md` for the source text.
-/

section Discussion_02_06a

variable {A : Type*} [CommRing A] [IsDomain A]
  {S : Type*} [CommRing S] [Algebra A S]
  (M : Submonoid A) [IsLocalization M S]

/-! ### Claim: I_𝔭 = IA_𝔭

The localization of an ideal I (viewed as an A-module) with respect to
a multiplicative set S is the same as the extension (image) of I under
the localization map A → S⁻¹A.

Mathlib captures this via `Algebra.idealMap_isLocalizedModule`: the map
`Algebra.idealMap I : I →ₗ[A] (I.map (algebraMap A S))` is a localized module,
meaning the target `I.map (algebraMap A S)` satisfies the universal property
of S⁻¹I. -/

-- The ideal extension map I → I.map(algebraMap A S) is a localized module
recall Algebra.idealMap_isLocalizedModule

/-- For a concrete `Localization`, the extension of an ideal I is the localized
module of I — i.e., the canonical S⁻¹A-submodule generated by I in S⁻¹A
equals I.map (algebraMap A (Localization M)). -/
example (I : Ideal A) :
    IsLocalizedModule M (Algebra.idealMap (S := Localization M) I) := inferInstance

end Discussion_02_06a
