import Mathlib

/-!
# Lemma 2.14: Fractional Ideal Characterization

**Lemma 2.14.** Let A be a noetherian domain with fraction field K, and let
I ⊆ K be an A-module. Then I is finitely generated if and only if aI ⊆ A for
some nonzero a ∈ A.

## Mathlib correspondence

Mathlib's `FractionalIdeal` uses the `IsFractional` predicate (∃ a ∈ A⁰,
a • I ⊆ A) as its *definition*. The equivalence with finite generation for
noetherian rings is:
- Forward (f.g. → IsFractional): built into `isFractional_span_singleton` and
  closure under sums/products
- Backward (IsFractional → f.g.): `FractionalIdeal.fg_of_isNoetherianRing`
-/

section Lemma_2_14

variable {A : Type*} [CommRing A] [IsDomain A] [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K] [IsFractionRing A K]

open FractionalIdeal

/-! ### The `IsFractional` predicate

This is the "aI ⊆ A" condition from the lemma. Mathlib uses this as the
*definition* of fractional ideals, rather than the "finitely generated" condition. -/

-- IsFractional S I means: ∃ a ∈ S, ∀ b ∈ I, a • b ∈ image(A → K)
#check @IsFractional

-- Every FractionalIdeal carries a proof of IsFractional
#check @FractionalIdeal.isFractional

/-! ### Forward direction: f.g. implies IsFractional

If I is generated by r₁/s₁, …, rₙ/sₙ, then a = s₁⋯sₙ satisfies aI ⊆ A.
In Mathlib, this is witnessed by closure of IsFractional under the relevant
operations (span of singletons, sums). -/

-- A singleton {x} in K is fractional (witnessed by the denominator of x)
#check @isFractional_span_singleton

-- IsFractional is closed under addition of submodules
#check @IsFractional.sup

-- IsFractional is closed under multiplication
#check @IsFractional.mul

/-! ### Backward direction: IsFractional implies f.g. (when A is noetherian)

If aI ⊆ A, then aI is an ideal of A, hence finitely generated (A is noetherian).
If a₁, …, aₙ generate aI, then a₁/a, …, aₙ/a generate I. -/

-- When A is noetherian, every fractional ideal is finitely generated
#check @FractionalIdeal.fg_of_isNoetherianRing

/-! ### The numerator-denominator decomposition

Mathlib provides `den` and `num` witnessing the IsFractional structure:
- `I.den ∈ A⁰` is the "a" in "aI ⊆ A"
- `I.num` is the ideal aI ⊆ A -/

-- The denominator: an element of the submonoid S witnessing IsFractional
#check @FractionalIdeal.den

-- The numerator: the ideal obtained by clearing denominators
#check @FractionalIdeal.num

-- Key relation: den(I) • I = num(I) (as submodules of K)
#check @FractionalIdeal.den_mul_self_eq_num

/-! ### Proof of the equivalence

We state the equivalence explicitly as a theorem, bridging the book's
"finitely generated" characterization with Mathlib's `IsFractional` predicate. -/

/-- **Lemma 2.14**: For a noetherian domain A, an A-submodule I of K is finitely
generated if and only if it satisfies `IsFractional`, i.e., there exists nonzero
a ∈ A with aI ⊆ A.

The forward direction holds for any domain (product of denominators of generators).
The backward direction uses that A is noetherian (aI is a f.g. ideal). -/
theorem fractional_iff_fg (I : FractionalIdeal (nonZeroDivisors A) K) :
    Submodule.FG (I : Submodule A K) ↔ IsFractional (nonZeroDivisors A) (I : Submodule A K) :=
  ⟨fun _ => I.isFractional,
   fun _ => fg_of_isNoetherianRing le_rfl I⟩

/-- Forward direction of Lemma 2.14: every fractional ideal over a noetherian
domain is finitely generated. -/
theorem fractionalIdeal_fg (I : FractionalIdeal (nonZeroDivisors A) K) :
    Submodule.FG (I : Submodule A K) :=
  fg_of_isNoetherianRing le_rfl I

end Lemma_2_14
