import Mathlib

/-!
# Lemma 2.18: The quotient I ÷ J is a fractional ideal

**Lemma 2.18.** Let I and J be fractional ideals of a noetherian domain A with
J nonzero. Then (I ÷ J) is a fractional ideal of A.

## Mathlib correspondence

Mathlib's `FractionalIdeal` type has a `Div` instance that constructs I / J
as a `FractionalIdeal` (not just a submodule), using `isFractional_div_of_ne_zero`
to prove the `IsFractional` predicate. This is exactly Lemma 2.18.

The proof in Mathlib follows a strategy similar to the book's: given witnesses
aI, aJ for I and J being fractional (so aI·I ⊆ A and aJ·J ⊆ A), pick a nonzero
y ∈ J, and show that aI · y' (where y' = aJ · y) witnesses (I ÷ J) being fractional.

See `blobs/Lecture2/02_18_Lemma.md` for the source text.
-/

section Lemma_2_18

variable {A : Type*} [CommRing A] [IsDomain A] [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K] [IsFractionRing A K]

open FractionalIdeal

/-! ### The IsFractional predicate for I / J

This is the core of Lemma 2.18: proving that the submodule I / J satisfies
the IsFractional predicate when J ≠ 0. -/

-- The underlying proof: IsFractional is preserved by submodule division
#check @IsFractional.div_of_nonzero

-- Specialized to FractionalIdeal: I / J is fractional
#check @FractionalIdeal.isFractional_div_of_ne_zero

/-! ### The Div instance

Mathlib constructs the division I / J as a FractionalIdeal directly, using
the proof above. This makes I / J well-typed as a FractionalIdeal. -/

-- I / J returns a FractionalIdeal (0 if J = 0)
#check (inferInstance : Div (FractionalIdeal (nonZeroDivisors A) K))

-- The coercion: ↑(I / J) = ↑I / ↑J as submodules
#check @FractionalIdeal.coe_div

/-! ### Lemma 2.18 as an explicit theorem

We state it in a form matching the book: for noetherian A, the quotient
I ÷ J is a fractional ideal (i.e., finitely generated as an A-module). -/

/-- **Lemma 2.18**: For fractional ideals I, J of a noetherian domain A with
J nonzero, I ÷ J is a fractional ideal. In Mathlib this is witnessed by the
fact that `I / J` has type `FractionalIdeal A⁰ K`, and the underlying
submodule is finitely generated by `fg_of_isNoetherianRing`. -/
theorem quotient_fractionalIdeal_fg
    (I J : FractionalIdeal (nonZeroDivisors A) K) (_hJ : J ≠ 0) :
    Submodule.FG (↑(I / J) : Submodule A K) :=
  fg_of_isNoetherianRing le_rfl (I / J)

/-! ### Key properties of the quotient

These are used in later results about invertibility (Lemma 2.20, etc.). -/

-- Membership: x ∈ I / J ↔ ∀ y ∈ J, x * y ∈ I
#check @FractionalIdeal.mem_div_iff_of_ne_zero

-- Lattice characterization: I ≤ J / J' ↔ I * J' ≤ J
#check @FractionalIdeal.le_div_iff_mul_le

end Lemma_2_18
