import Mathlib

/-!
# Definition 2.13: Fractional Ideal

A *fractional ideal* of a noetherian domain A is a finitely generated A-submodule
of its fraction field.

## Mathlib correspondence

Mathlib's `FractionalIdeal S P` defines fractional ideals as A-submodules I of P
(an algebra over Localization S) satisfying `IsFractional S I`, i.e., there exists
`a ∈ S` with `a • I ⊆ 1`. For noetherian domains with `S = A⁰` (nonzero elements),
this coincides with the book's "finitely generated A-submodule of K" definition.

The key bridge: `FractionalIdeal.fg_of_isNoetherianRing` shows that when A is
noetherian, every Mathlib fractional ideal is finitely generated.
-/

section FractionalIdeal_Def

/-! ### The definition

**Definition 2.13.** A fractional ideal of a noetherian domain A is a finitely
generated A-submodule of its fraction field.

Mathlib's `FractionalIdeal` uses the equivalent characterization: an A-submodule I
of K such that there exists a nonzero `a ∈ A` with `a • I ⊆ A`. -/

-- The type of fractional ideals: submodules I of P with ∃ a ∈ S, a • I ⊆ 1
#check @FractionalIdeal

-- The predicate: I is fractional if ∃ a ∈ S, ∀ b ∈ I, a * b ∈ 1
#check @IsFractional

/-! ### Bridge: Mathlib ↔ Book definition

The book defines fractional ideals as *finitely generated* A-submodules of K.
Mathlib uses the `IsFractional` predicate (∃ a ∈ A⁰, a • I ⊆ A). For noetherian
rings, these are equivalent:

- Every Mathlib fractional ideal is f.g. when A is noetherian (`fg_of_isNoetherianRing`)
- Every f.g. A-submodule of K satisfies `IsFractional` (clear: if I = ⟨x₁/s₁,…,xₙ/sₙ⟩
  then a = s₁⋯sₙ works)
-/

variable {A : Type*} [CommRing A] [IsDomain A] [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K] [IsFractionRing A K]

-- When A is noetherian, every fractional ideal (in Mathlib's sense) is f.g.
#check @FractionalIdeal.fg_of_isNoetherianRing

-- Demonstrate: fractional ideals over the nonzero elements of A in K
example : Type _ := FractionalIdeal (nonZeroDivisors A) K

/-! ### Coercion from ideals

Every ideal of A is a fractional ideal (embedded via `coeIdeal`). -/

-- The coercion: Ideal A → FractionalIdeal A⁰ K
#check @FractionalIdeal.coeIdeal

-- Ideals, viewed as fractional ideals, are contained in A (i.e., ≤ 1)
#check @FractionalIdeal.coeIdeal_le_one

/-! ### Fractional ideals need not be contained in A

The book notes that fractional ideals generalize ideals: every ideal is a
fractional ideal, but fractional ideals need not be contained in A.
We witness this by showing that not every fractional ideal is ≤ 1. -/

-- A nonzero principal fractional ideal generated by a unit can exceed 1.
-- For example, the fractional ideal (2⁻¹) in Frac(ℤ) is not ≤ 1.
-- This is captured by the general algebraic structure:
#check @FractionalIdeal.spanSingleton_mul_spanSingleton

/-! ### Algebraic structure

Fractional ideals form a commutative semiring and a lattice. -/

example : CommSemiring (FractionalIdeal (nonZeroDivisors A) K) := inferInstance

example : Lattice (FractionalIdeal (nonZeroDivisors A) K) := inferInstance

end FractionalIdeal_Def
