import Mathlib

/-!
# Definition 2.17: Principal Fractional Ideal

A fractional ideal of A is *principal* if it is generated by one element,
that is, it has the form xA for some x ∈ K. We write (x) := xA for the
principal fractional ideal generated by x ∈ K.

## Mathlib correspondence

Mathlib defines `FractionalIdeal.spanSingleton S x` as the fractional ideal
generated by a single element `x`. For `S = A⁰` (the nonzero divisors of A),
`spanSingleton A⁰ x` corresponds to the book's `(x) = xA`.
-/

section PrincipalFractionalIdeal

variable {A : Type*} [CommRing A] [IsDomain A]
variable {K : Type*} [Field K] [Algebra A K] [IsFractionRing A K]

open FractionalIdeal

/-! ### The definition

**Definition 2.17.** A fractional ideal of A is *principal* if it has the form
xA for some x ∈ K. In Mathlib this is `FractionalIdeal.spanSingleton`. -/

-- The principal fractional ideal (x) = xA
#check @FractionalIdeal.spanSingleton
  -- spanSingleton : S → K → FractionalIdeal S K

/-! ### Key properties of principal fractional ideals -/

-- (1) = A (the unit fractional ideal)
#check @FractionalIdeal.spanSingleton_one
  -- spanSingleton A⁰ 1 = 1

-- (0) = 0 (the zero fractional ideal)
#check @FractionalIdeal.spanSingleton_zero
  -- spanSingleton A⁰ 0 = 0

-- (x) · (y) = (xy)
#check @FractionalIdeal.spanSingleton_mul_spanSingleton
  -- spanSingleton A⁰ x * spanSingleton A⁰ y = spanSingleton A⁰ (x * y)

/-! ### Membership characterization -/

-- z ∈ (x) ↔ ∃ a ∈ A, z = a • x
#check @FractionalIdeal.mem_spanSingleton
  -- y ∈ spanSingleton S x ↔ ∃ z : R, algebraMap R K z * x = y

/-! ### Every principal fractional ideal generated by a nonzero element is invertible -/

-- (x) · (x⁻¹) = 1 for x ≠ 0
#check @FractionalIdeal.spanSingleton_mul_inv
  -- spanSingleton A⁰ x * (spanSingleton A⁰ x)⁻¹ = 1

-- (x⁻¹) = (x)⁻¹
#check @FractionalIdeal.spanSingleton_inv
  -- spanSingleton A⁰ x⁻¹ = (spanSingleton A⁰ x)⁻¹

end PrincipalFractionalIdeal
