import Mathlib

/-!
# Discussion: Operations on Fractional Ideals

See `blobs/Lecture2/02_17a_Discussion.md` for the source text.

This discussion introduces three operations on fractional ideals:
- Addition: I + J = {i + j : i ∈ I, j ∈ J}
- Multiplication: IJ = A-module generated by {ij : i ∈ I, j ∈ J}
- Quotient (colon ideal): I ÷ J = {x ∈ K : xJ ⊆ I}

It also notes that I ÷ J is NOT a module quotient, and that for principal
fractional ideals (x) ÷ (y) = (x/y).
-/

section FractionalIdealOps

variable {A : Type*} [CommRing A] [IsDomain A] [IsNoetherianRing A]
variable {K : Type*} [Field K] [Algebra A K] [IsFractionRing A K]

open FractionalIdeal

/-! ### Claim 1: Addition of fractional ideals

I + J := {i + j : i ∈ I, j ∈ J}

In Mathlib, addition of fractional ideals is defined as the supremum (join)
in the submodule lattice. The membership characterization is:
x ∈ I + J ↔ ∃ i ∈ I, ∃ j ∈ J, i + j = x -/

-- Addition is the lattice join
#check @FractionalIdeal.sup_eq_add

-- Membership characterization: x ∈ I + J ↔ ∃ i ∈ I, ∃ j ∈ J, i + j = x
#check @FractionalIdeal.mem_add

/-! ### Claim 2: Multiplication of fractional ideals

IJ := A-module generated by {ij : i ∈ I, j ∈ J}

In Mathlib, multiplication is defined via the underlying submodule multiplication,
which is the span of pairwise products. -/

-- i ∈ I, j ∈ J implies i * j ∈ I * J
#check @FractionalIdeal.mul_mem_mul

-- I * J ≤ K ↔ ∀ i ∈ I, ∀ j ∈ J, i * j ∈ K
#check @FractionalIdeal.mul_le

/-! ### Claim 3: Quotient (colon) ideal

I ÷ J := {x ∈ K : xJ ⊆ I}

In Mathlib, this is `FractionalIdeal / J` using the submodule division.
The membership characterization is: x ∈ I / J ↔ ∀ y ∈ J, x * y ∈ I. -/

-- The membership characterization of I / J
#check @FractionalIdeal.mem_div_iff_of_ne_zero

-- I ÷ J is a fractional ideal (when J ≠ 0)
#check @FractionalIdeal.isFractional_div_of_ne_zero

-- The lattice characterization: I ≤ J / J' ↔ I * J' ≤ J
#check @FractionalIdeal.le_div_iff_mul_le

/-! ### Claim 4: I ÷ J is NOT a module quotient

The book emphasizes: "I ÷ J is **not** a quotient of A-modules (for example,
ℤ ÷ ℤ = ℤ but ℤ/ℤ = {0})."

This is a conceptual remark — the notation I ÷ J (colon ideal) vs I/J (module quotient)
refer to completely different operations. No Lean statement needed beyond the
documentation. -/

/-! ### Claim 5: For principal fractional ideals, (x) ÷ (y) = (x/y)

This generalizes division in K×. -/

-- (x) / (y) = (x / y) for elements of the fraction field
#check @FractionalIdeal.spanSingleton_div_spanSingleton

-- Self-division: (x) / (x) = 1 for x ≠ 0
#check @FractionalIdeal.spanSingleton_div_self

end FractionalIdealOps
